[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Astro builds to dist/)
  publish = "dist"

[build.environment]
  # Node version for builds
  NODE_VERSION = "18"

# Redirect rules for better SEO (optional)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# Headers for performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/interviews/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

# Development context
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"